FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY bewise_app /app/bewise_app

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "bewise_app.main:app", "--host", "0.0.0.0", "--port", "8000"]

